---
language: objective-c
osx_image: xcode7.3
before_install:
  - brew uninstall xctool && brew install --HEAD xctool
script: xctool -project Link.xcodeproj -scheme Link -sdk iphonesimulator test
branches:
  only:
  - master
  - /^\d.*$/
